### ISSUE TITLE
Scan on mobile apps with existing agents shows no findings

### ISSUE THREAD

**Issue by RabsonJ** [Ostorlab/oxo#302]
**Describe the bug**
Running a scan of mobile apps with existing agents reports no findings even if the apps are vulnerable.

**To Reproduce**
1. Run a scan with

**Expected behavior**
`ostorlab vulnz list -s [scan_id]` should list the vulnerabilities of the mobile apps.

**Screenshots**
![image001](https://user-images.githubusercontent.com/52573181/177739956-fe67cd7e-15b2-43bb-8139-c8b0344fbb30.png)

**Link to the apps**
[https://www.linkedin.com/pulse/10-vulnerable-android-applications-beginners-learn-hacking-anugrah-sr](https://www.linkedin.com/pulse/10-vulnerable-android-applications-beginners-learn-hacking-anugrah-sr)

**Comment by amine3** [comment]
Hi,
Which command did you use to run the scan?

**Comment by Jasonchenya** [comment]
hi Amine,

Please check the following command:
ostorlab scan run --agent agent/ostorlab/nmap --agent agent/ostorlab/openvas --agent agent/ostorlab/tsunami --agent agent/ostorlab/nuclei android-apk dvba_v1.1.0.apk

**Comment by Jasonchenya** [comment]
Hi Amine, 
Noted with thanks! Is there any plan to release any agents that support the mobile analysis?  Also could you help check the Connection reset issue for the network scan with single ip address?

**Comment by deadly-panda** [comment]
We have created an [issue](https://github.com/Ostorlab/ostorlab/issues/301) for the connection reset bug, and have one of the team working on a fix.
Yes, we are working on open-sourcing all of our scanning agents, web and mobile among others.
