### ISSUE TITLE
Update Request for APK and IPA Scanning Agents

### ISSUE THREAD

**Issue by MrR10T** [Ostorlab/oxo#659]
Hello,
I have been using Ostorlab for security scanning in general and considering I'm doing even some mobile security testing I noticed that the agents for APK and IPA file scans have been missing from the GitHub repository (at least for what is related to the CLI usage). 

I also observed mentions about the potential release of these agents, including for the command line interface, around two years ago. Could you provide an update on the status of the scanning agents for APK and IPA files? Are there any plans to update these components in the near future?

Thank you for your efforts on this essential tool, and I look forward to any updates you might have.

Best regards,
Alberto

**Comment by 3asm** [comment]
The mobile agents require some major additions to ease exposing access to mobile devices (actual phones connected using USB). 

We are working on adding these capabilities but it will take some time to make sure all the setup is automated and pain-free.

**Comment by MrR10T** [comment]
Hello, this is marked as completed but Am I wrong or agents for mobile are still not available?
