### ISSUE TITLE
Need cloud account to build agents locally

### ISSUE THREAD

**Issue by laurentsimon** [Ostorlab/oxo#749]
**Describe the bug**

I'm following the template example and running:

```shell
$ oxo --version
oxo, version 1.0.30

$ oxo agent build -f oxo.yaml
docker.errors.DockerException: Credentials store error: StoreError('docker-credential-gcloud not installed or not available in PATH')
```

**To Reproduce**
See above description

**Expected behavior**
Need not a a GCP account or provide credentials to build an agent locally.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 N/AA

**Additional context**

**Comment by 3asm** [comment]
We are investigating, but I suspect this is because of your Docker setup. Do you have `gcloud` installed on your machine?

**Comment by laurentsimon** [comment]
Looks like it's a docker config problem https://stackoverflow.com/questions/61933284/docker-compose-asking-for-gcloud-credentials. Closing.

(I don't want to give docker gcloud access if it does not need it - this case.)
