### ISSUE TITLE
question: custom message protos

### ISSUE THREAD

**Issue by laurentsimon** [Ostorlab/oxo#750]
This issue is a question, not a feature request.

IIUC, messages must be one of the protos defined in https://github.com/Ostorlab/oxo/blob/main/src/ostorlab/agent/message/proto/v3. 

So to customize the protos, I may use the [control proto](https://github.com/Ostorlab/oxo/blob/main/src/ostorlab/agent/message/proto/v3/control/control.proto) and define my own format in the [message field](https://github.com/Ostorlab/oxo/blob/main/src/ostorlab/agent/message/proto/v3/control/control.proto#L14)?

I'm not sure that's the intended way, and I'd like some feedback whether there's a cleaner way to achieve what I'm asking.

Thanks!

**Comment by 3asm** [comment]
Not really, you can instead use the [`emit_raw`](https://github.com/Ostorlab/oxo/blob/main/src/ostorlab/agent/agent.py#L359) method that accepts a byte and format the message in whatever serialization format you want:
