### ISSUE TITLE
openvas agent stuck in loop

### ISSUE THREAD

**Issue by rfhacker** [Ostorlab/oxo#755]
Installed on a kali linux system and it started this and assumed it was because Kali, so i installed a fresh Ubuntu box and getting same results.

When running the first scan example, i dont really notice any errors thrown, but the building of the openvas database seems to get stuck in a loop.  The current GVMd database version is 255 each time it iterates through.  The image feeds and installed feeds remain the same as well.

It seems to try 'Running first start configuration' over and over, using a different named tmp file each time (such as /tmp/tmp.4Qbo6s1bNC).

Any ideas for this, or missing steps in the setup?

thanks!

**Comment by rfhacker** [comment]
Just to add, i also ran it again leaving off the openvas agent.  It seems that the scans complete, as i see "Done scanning targets." for both tsunami and nuclei...but it just sits there at this point and does nothing.  I list scans and it still shows running.  It has stayed this way overnight for the single ip of 8.8.8.8.  I get the same results running the straight docker command.  Are there some steps missing in the documentation for setting up yaml files or databases or something?  Or perhaps this project hasn't updated for any latest tool updates?

**Comment by Nomadyb** [comment]
Hi sir  I’m experiencing the same issue. Is there any other solution for an OpenVAS agent?

**Comment by 3asm** [comment]
We will try to look into it. Not the best answer, but `Nuclei`, `Tsunami`, `Metasploit` and `Asteroid` agents are very capable put together.

**Comment by Nomadyb** [comment]
Yes, thank you very much. The project is really great. My goal was this: I use GVM to perform scans with the help of Python and SSH, but unfortunately, OpenVAS doesn’t have an agent structure. I want to create an alternative for this
