### ISSUE TITLE
 i want to re-use containers to run multiple scans . 

### ISSUE THREAD

**Issue by vishal-spektrum** [Ostorlab/oxo#798]
is this possible in free community version to run multiple scans by re-using containers.

and is it production ready environment code .

**Comment by 3asm** [comment]
Hi Vishal,

The same OSS OXO engine is used to run Ostorlab production. Containers are lightweight to run and the engine with the `tracker` agent handles managing their lifecycle to close them once the scan has completed.

There is however a limit to what you can run on a single machine, you will be limited by your CPU, memory, max processes, max sockets, bandwidth, you name it.

If the expectation is to run 100 instances, on the same machine, you ought to have a very large instance to do so. Even other OSS projects like Nuclei or Semgrep run on their own will result in spikes in memory or CPU.

I hoe this helps.
