### ISSUE TITLE
get the output of ostrolab in microsoft SQL server database instead of sqlite

### ISSUE THREAD

**Issue by vishal-spektrum** [Ostorlab/oxo#800]
i want to get the output of scans in my  Micrsooft sql server
how can i make the output to go into my custom tables ?

**Comment by 3asm** [comment]
To achieve that, you should implement a persist vulnerability agent, like (agent persist vulnz)[https://github.com/Ostorlab/agent_persist_vulnz] that will connect to the database and persist the vulnerability messages.

You then need to add the agent to the list of agents you start in your scan.
